name: Docker Image Publish 

on:
  push:
    branches:
      - patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to ACR
      uses: azure/docker-login@v2
      with:
        login-server: aztestwestus3backendacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push
      run: |
        IMAGE_NAME=aztestwestus3backendacr.azurecr.io/sample-app-aoai-chatgpt

        TAG=patch1-${{ github.run_number }}

        echo "Using tag: $TAG"

        docker build . --no-cache --file WebApp.Dockerfile --tag $IMAGE_NAME:$TAG
        docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:latest
